### ISSUE TITLE
Issues in log function of FluentLogger class

### ISSUE THREAD

**Issue by iampiyush** [fluent/fluent-logger-java#31]
Issues in latest version (0.3.1)

public boolean log(String tag, Map<String, Object> data) 

This function never returns false, even if we don't have valid host name.

flush function in RawSocketAppender class doesn't have any return type. So if there is IO Exception, this function will catch it , logs it , but no signal send to caller. Hence, log function will be returning true , even if we are not able to write. (Line no. 178-192 )

**Comment by komamitsu** [comment]
I'm going to close this issue. You can detect network errors using https://github.com/fluent/fluent-logger-java/blob/master/src/main/java/org/fluentd/logger/errorhandler/ErrorHandler.java.
