### ISSUE TITLE
Does FluentLogger class provide a way to get a sender instance?

### ISSUE THREAD

**Issue by moznion** [fluent/fluent-logger-java#44]
I want to get a Sender instance from an instance of FluentLogger, but I could not be located such as a method. Is there a way to do that?

In particular, I wouldn't mind doing as the following.
https://github.com/moznion/fluent-logger-mock-sender

**Comment by repeatedly** [comment]
@muga @komamitsu @oza Could you handle this?

**Comment by komamitsu** [comment]
@moznion Sorry for my late reply. I fixed this issue in #46 and released a new version.

**Comment by moznion** [comment]
Thank you very much!
