### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by sanoyphilippe** [fluent/fluent-logger-java#61]
Tested sending 4 million logs of data to fluentd using fluent-logger-java. And we were testing the buffer of fluent-logger. We send to a log forwarder which sends it to an aggregator. The aggregator writes it into the postgresql database. Tried disallowing the connection of the aggregator to the database so that the buffer would be filled up.
However at around 2 million logs worth of data trying to be sent through fluent logger java, this error occurred. 

We were thinking if it were possible to check how much data is in the buffer already. Is there a way for us to check the current buffer size of fluent-logger-java?
@repeatedly @komamitsu

**Comment by sanoyphilippe** [comment]
Exception in thread "Operation thread " java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.msgpack.io.BufferedOutput.allocateNewBuffer(BufferedOutput.java:37)
	at org.msgpack.io.BufferedOutput.write(BufferedOutput.java:69)
	at org.msgpack.io.LinkedBufferOutput.write(LinkedBufferOutput.java:22)
	at org.msgpack.packer.MessagePackPacker.writeByteArray(MessagePackPacker.java:204)
	at org.msgpack.packer.MessagePackPacker.writeString(MessagePackPacker.java:236)
	at org.msgpack.packer.AbstractPacker.write(AbstractPacker.java:191)
	at org.msgpack.template.StringTemplate.write(StringTemplate.java:38)
	at org.msgpack.template.StringTemplate.write(StringTemplate.java:25)
	at org.msgpack.template.AbstractTemplate.write(AbstractTemplate.java:27)
	at org.msgpack.packer.AbstractPacker.write(AbstractPacker.java:203)
	at org.fluentd.logger.sender.Event$EventTemplate.write(Event.java:76)
	at org.fluentd.logger.sender.Event$EventTemplate.write(Event.java:55)
	at org.msgpack.template.AbstractTemplate.write(AbstractTemplate.java:27)
	at org.msgpack.MessagePack.write(MessagePack.java:196)
	at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:140)
	at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:129)
	at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:124)
	at org.fluentd.logger.FluentLogger.log(FluentLogger.java:101)
	at org.fluentd.logger.FluentLogger.log(FluentLogger.java:86)
	at jp.co.sharp.logmng.regist.service.impl.FluentD$1FluentDThread.run(FluentD.java:113)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sanoyphilippe** [comment]
`public class FluentD {
	private static FluentLogger FluentDLogger = null;
	//public static List<Map<String, Object>> logDataList = Collections.synchronizedList(new ArrayList<Map<String, Object>>());
	public static Vector<Map<String, Object>> logDataList = new Vector<Map<String,Object>>();
public static void main(String[] args) {
		// TODO Auto-generated method stub

		class FluentDThread implements Runnable {
			private Thread t;
			private String threadName;

			FluentDThread(String name) {
				threadName = name;
				System.out.println("Creating " + threadName);
			}

			FluentDThread(String name, Map<String, Object> data) {
				threadName = name;
				FluentD.logDataList.add(data);
				System.out.println("Creating " + threadName);
			}

			@Override
			public void run() {
				try {
					while(true) {
						//FluentDLogger.flush();
						if (!logDataList.isEmpty()) {
							System.out.println(logDataList.size());
							System.out.println("not empty");
							if (FluentDLogger.isConnected()) {
								FluentDLogger.log("fluentdoperationlogs",
										FluentD.logDataList.remove(0));
								FluentDLogger.flush();
								System.out.println("Success");
							} else {
								while (!FluentDLogger.isConnected()) {
									System.out.println("Fail sending of log");
									FluentDLogger.log("fluentd", FluentD.logDataList.remove(0));
									FluentDLogger.flush();

								}
								System.out.println("Success");
							}
						} else {
							//System.out.println("empty");
						}
					}
				} catch (Exception e) {
					e.printStackTrace();
					Logger.addLog(this.getClass(), "FluentDに接続できません", LogLevel.ERROR);
				} finally {
					System.out.println("Thread has ended");
					FluentDLogger.close();
				}
			}

			public void start() {
				System.out.println("Starting " + threadName);
				if (t == null) {
					t = new Thread(this, threadName);
					t.start();
				}
			}
		}


		System.out.println(System.getenv("LOGMNG_HOST_ADDRESS"));
		System.out.println(System.getenv("LOGMNG_HOST_PORT"));
		FluentDLogger = FluentLogger.getLogger("postgresql", System.getenv("LOGMNG_HOST_ADDRESS"),
				Integer.parseInt(System.getenv("LOGMNG_HOST_PORT")));
		FluentDThread fluentThread = new FluentDThread("Operation thread ");
		fluentThread.start();
		int i;
		for (i = 1; i <= 4000000; i++) {
			Calendar c = Calendar.getInstance();
			c.set(Calendar.YEAR, 2016);
			c.set(Calendar.MONTH, Calendar.MARCH);
			c.set(Calendar.DAY_OF_MONTH, 1);
			Date date = c.getTime();
			SimpleDateFormat dateFormatter = new SimpleDateFormat("dd-MM-yyyy");
			SimpleDateFormat timeFormatter = new SimpleDateFormat("HH:mm:ss.SSS");

			String dateAsString = dateFormatter.format(date);
			String timeAsString = timeFormatter.format(date);

			Map<String, Object> logData = new HashMap<String, Object>();
			logData.put("id", i);
			logData.put("did", "");
			logData.put("date", dateAsString);
			logData.put("time", timeAsString);
			logData.put("fseq", "04");
			logData.put("hname", "adsasdsa");
			logData.put("pseq", "02");
			logData.put("usercode", "basdasdas");
			logData.put("splace", "system");
			logData.put("op", "popowashere@gmail.com");
			logData.put("skbn", "2");
			logData.put("ipAdd", "12.143.242.55");
			logData.put("resCode", "2");
			logData.put("subsysCode", "03");
			logData.put("suppInfo",
					"adsadsadas");
			logDataList.add(logData);
		}`

**Comment by repeatedly** [comment]
@komamitsu Does fluency have that functionality?

**Comment by komamitsu** [comment]
@sanoyphilippe fluent-logger-java doesn't support that feature. As @repeatedly mentioned, https://github.com/komamitsu/fluency provides the feature.

Fluency allocates memory internally for buffering data and expands buffer if needed. You can know the size of allocated buffer with `Fluency#getAllocatedBufferSize` and the size of actual buffered data with `Fluency#getBufferedDataSize`. Also, if you need high throughput for sending event data to Fluentd, Fluency would be better.
