### ISSUE TITLE
API changes report for Fluent Logger

### ISSUE THREAD

**Issue by lvc** [fluent/fluent-logger-java#70]
Hi,

I'd like to share the report on backward binary compatibility and API changes for the library: https://abi-laboratory.pro/java/tracker/timeline/fluent-logger/

The report is generated by the https://github.com/lvc/japi-compliance-checker tool for jars found at http://central.maven.org/maven2/org/fluentd/fluent-logger/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![fluent-logger-2](https://user-images.githubusercontent.com/1517837/31269595-c91ea55a-aa89-11e7-9eb4-a9a6ecc7ebe7.png)
![fluent-logger-1](https://user-images.githubusercontent.com/1517837/31269596-c920234e-aa89-11e7-831b-eb333933bd6f.png)

**Comment by komamitsu** [comment]
Interesting. Thanks.
