### ISSUE TITLE
Release 0.3.4? 

### ISSUE THREAD

**Issue by tratch** [fluent/fluent-logger-java#85]
It looks like there are some important updates committed to source. Any chance you could please cut a new release and push to maven?

**Comment by agsimeonov** [comment]
My colleagues and I would also be highly interested in a new release with all the changes since the last release.  While comprising of mostly bugfixed  the cchanges do indeed seem important:

**Comment by komamitsu** [comment]
Just released 0.3.4.

BTW, if you're using fluent-logger-java heavily, you might also be interested in https://github.com/komamitsu/fluency.
